name: Github Actions
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # TODO switch to setup-nim-action@v5 and use nimby
    - uses: treeform/setup-nim-action@v2
    # - run: nimble install -y -d
    # manually install dependencies since nimble and nimby are both giving issues
    # silky requires the latest shady on git, there hasn't been a release yet.
    - run: cd ../ && git clone https://github.com/treeform/silky && cd silky && nimble install -y
    - run: cd ../ && git clone https://github.com/treeform/shady && cd shady && nimble install -y
    - run: nim c src/Typos.nim
