name: Github Actions
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # TODO switch to setup-nim-action@v5 and use nimby
    - uses: treeform/setup-nim-action@v2
    - run: nimble install -y -d
    # TODO fix
    # - run: nim c src/Typos.nim
