name: Github Actions
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: treeform/setup-nim-action@v5
    # cache is giving me issues on gitea
    # - uses: actions/cache@v3
    #   with:
    #     path: ~/.nimby
    #     key: ${{ runner.os }}-nimby-${{ hashFiles('Typos.nimble') }}
    #     restore-keys: |
    #       ${{ runner.os }}-nimby-
    - run: nimby install -g -V Typos.nimble
    - run: ls -la ~/.nimby/pkgs/
    - run: nim r tests/test.nim
